### ISSUE TITLE
Problems connecting

### ISSUE THREAD

**Issue by Zeddy-** [droidifi/newracom-s1g#1]
![image](https://user-images.githubusercontent.com/1147662/115707587-a800ea00-a377-11eb-972e-eb15363101af.png)

On the client i get this in DMESG 
[Thu Apr 22 06:31:39 2021] nrc80211 nrc80211: WIM_TLV_PS_ENABLE(0)
[Thu Apr 22 06:31:39 2021] Failed to load board data, error:1
[Thu Apr 22 06:31:39 2021] nrc80211 nrc80211: bd is NULL

Any idea? :)

**Comment by Zeddy-** [comment]
I thought maybe it was because i was using the wrong country so i set this in  **/etc/modprobe.d/nrc.conf**

options nrc fw_name=nrc7292_cspi.bin hifspeed=16000000 fw_country=EU

and in **/etc/hostapd/ap_halow_sae_s1g.conf**

ctrl_interface=/var/run/hostapd
country_code=FI
interface=wlan1
ssid=droidifi
hw_mode=ah

channel=41
#channel=922000

And get this error when starting the AP:
pi@raspberrypi:~ $ sudo hostapd /etc/hostapd/ap_halow_sae_s1g.conf
wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Could not determine operating frequency
wlan1: interface state COUNTRY_UPDATE->DISABLED
wlan1: AP-DISABLED
wlan1: Unable to setup interface.
wlan1: interface state DISABLED->DISABLED
wlan1: AP-DISABLED
wlan1: CTRL-EVENT-TERMINATING
hostapd_free_hapd_data: Interface wlan1 wasn't started
nl80211: deinit ifname=wlan1 disabled_11b_rates=0
pi@raspberrypi:~ $

**Comment by Zeddy-** [comment]
Also noticed that if i just assign it channel 161 according to newracoms example for US, even the US configuration fails. It only seems to work with this undocumented 922000 channel

#channel=161
channel=922000

**Comment by droidifi** [comment]
The new module uses 802.11ah S1G calls for any kernel at version 5.10 or newer. Channels are described in KHz (i.e. 909.5 MHz would be 909500 in the hostapd or wpa_supplicant config files). This requires using a modified version of hostapd, wpa_supplicant that understand channels in KHz.

The original Newracom driver presents itself to the Linux kernel as 802.11g/ac hardware and internally maps 2.4 GHz and 5 GHz channels to 802.11ah channels. For kernels older than 5.10 this behavior is preserved.

The new code is designed as a stepping stone to full S1G capability and is a WIP.

**Comment by Zeddy-** [comment]
Thanks for the reply, and for your work 👍 

Yes i figured there is some adjustments necessary and just wanted to quickly try it out, which is why i took your prebuilt  image and flashed two raspberries, set one as AP and one as client

I actually managed to get the client to the point where it saw the AP's MAC address and attempted to authenticate, but after a reboot of both that no longer worked. 

I tried playing around the with the channel value as i i also figured it might be KHz, but i can't see a frequency of 922MHz in the channel list, nor did it work after chaning the value to 920500 for example.

**Comment by Zeddy-** [comment]
Just to add to this, i reflashed my both cards and set the frequency country codes and frequencies according to the list and no longer get the error. But on both devices i get the following in dmesg 

[Thu Apr 22 16:15:25 2021] Failed to load board data, error:1
[Thu Apr 22 16:15:25 2021] nrc80211 nrc80211: bd is NULL
[Thu Apr 22 16:15:25 2021] cryptd: max_cpu_qlen set to 1000
[Thu Apr 22 16:15:25 2021] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready

**Comment by droidifi** [comment]
These are benign AFAIK, we don't use board data to set params.

**Comment by Zeddy-** [comment]
Just to clear up my setup:
Raspberry PI 4Gb, 2pieces
ALFA Netowrk's 802.11ah PiHAT module -- AHPI7292S, 2 pieces
Antennas for 802.11ah frequencies with IPEX connectors, 2 pieces

wiring according to this:
![image](https://user-images.githubusercontent.com/1147662/115869389-7d319700-a446-11eb-9a58-796c0a6bfdbb.png)

Both newly flashed (a few times) with the image you provided, changed the country codes and frequencies as you describe here and try to start the AP and the client:

![image](https://user-images.githubusercontent.com/1147662/115868917-d1884700-a445-11eb-8fb0-1e75cb33f1aa.png)

AP starts fine, client gives this error. Then i do wpa_supplicant killall and try again:
![image](https://user-images.githubusercontent.com/1147662/115869041-fda3c800-a445-11eb-9dc3-d8f3dbac7a08.png)

After this nothing happends.

Is there anyway to see what is happening in the background? 

I also noticed i have to SPI devices attach according to /dev, and on the image SPI itself seems to be disabled by default.

**Comment by droidifi** [comment]
What does your hostapd/ap_halow_sae_s1g.conf file look like?

Make sure the system launched wpa_supplicant is not running on either device before launching hostapd/wpa_supplicant ('sudo killall wpa_supplicant' after loading modules).

**Comment by Zeddy-** [comment]
So should i disable Wifi in raspi-config?

```
ctrl_interface=/var/run/hostapd
country_code=FI
interface=wlan1
ssid=droidifi
hw_mode=ah

channel=836000

#1MHz
#909.5MHz
#channel=37
#915.5MHz
#channel=43
#922.5MHz
#channel=150

#2MHz
#909MHz
#channel=153
#915MHz
#channel=156
#921MHz
#channel=159
#925MHz
#channel=161

#4MHz
#910MHz
#channel=162
#914MHz
#channel=163
#922MHz
#channel=165

ieee80211h=1
ieee80211d=1
ieee80211n=0
ieee80211w=2
#wmm_enabled=1
macaddr_acl=0
driver=nl80211
beacon_int=100
#disable_sgi=0
#ap_max_inactivity=3
ap_max_inactivity=16780
# USF=0, UI=2 : 3
# USF=1, UI=2 : 16780
# USF=0, UI=10: 11
# USF=1, UI=10: 16788
#listen_interval=2

#WPA3-SAE
#auth_alg=1 #1=wpa, 2=wep, 3=open
wpa=2      # wpa2 only
wpa_key_mgmt=SAE
wpa_pairwise=CCMP
rsn_pairwise=CCMP
wpa_passphrase=12345678
```

**Comment by droidifi** [comment]
This should work as long as you loaded the nrc7292 module with parameter "fw_country=EU".

Example:
insmod /lib/modules/$(uname -r)/extra/nrc.ko fw_name=nrc7292_cspi.bin hifspeed=16000000 fw_country=EU

**Comment by Zeddy-** [comment]
Hi, yes that's what i did. 

I noticed the kernel modules seem to be loaded allready in the image, iwconfig shows wlan1 after reboot:

```
pi@raspberrypi:~ $ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

wlan1     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

```
Loading module does not work, got the same error after first boot as well:
```
pi@raspberrypi:~ $ sudo modprobe mac80211
pi@raspberrypi:~ $ sudo insmod /lib/modules/$(uname -r)/extra/nrc.ko fw_name=nrc7292_cspi.bin hifspeed=16000000 fw_country=[US,EU,JP,TW,KR,CN]
insmod: ERROR: could not insert module /lib/modules/5.10.20-v8/extra/nrc.ko: File exists

```
So basically after rebooting the raspberry i should immediately run 
sudo killall wpa_supplicant

And then 
```
ip addr add 192.168.200.1/24 dev wlan1
hostapd /etc/hostapd/ap_halow_sae_s1g.conf
```

Or
```
ip addr add 192.168.200.2/24 dev wlan1
wpa_supplicant -iwlan1 -Dnl80211 -c /etc/wpa_supplicant/sta_halow_sae_s1g.conf 
```
Correct? :)

**Comment by Zeddy-** [comment]
![image](https://user-images.githubusercontent.com/1147662/115927731-8c880300-a48d-11eb-836a-92912c733109.png)

AP on the left
```ctrl_interface=/var/run/hostapd
country_code=FI
interface=wlan1
ssid=droidifi
hw_mode=ah

channel=863500
#channel=917000
#channel=918000
#channel=92200
#1MHz
#909.5MHz
#channel=37
#915.5MHz
#channel=43
#922.5MHz
#channel=150

#2MHz
#909MHz
#channel=153
#915MHz
#channel=156
#921MHz
#channel=159
#925MHz
#channel=161

#4MHz
#910MHz
#channel=162
#914MHz
#channel=163
#922MHz
#channel=165

ieee80211h=1
ieee80211d=1
ieee80211n=0
ieee80211w=2
#wmm_enabled=1
macaddr_acl=0
driver=nl80211
beacon_int=100
#disable_sgi=0
#ap_max_inactivity=3
ap_max_inactivity=16780
# USF=0, UI=2 : 3
# USF=1, UI=2 : 16780
# USF=0, UI=10: 11
# USF=1, UI=10: 16788
#listen_interval=2

#WPA3-SAE
#auth_alg=1 #1=wpa, 2=wep, 3=open
wpa=2      # wpa2 only
wpa_key_mgmt=SAE
wpa_pairwise=CCMP
rsn_pairwise=CCMP
wpa_passphrase=12345678
```

Client on the right:
```
ctrl_interface=/var/run/wpa_supplicant

country=FI
update_config=1
network={
    ssid="droidifi"
    proto=RSN
    key_mgmt=SAE
    pairwise=CCMP
    group=CCMP
    psk="12345678"
    ieee80211w=2
#BW.11ah(Freq) 1.37(909.5) 1.43(915.5) 1.150(922.5) 2.153(909) 2.156(915) 2.159$
#    freq_list=        5185        5215         5750      5765       5780      $
#    scan_freq=        5185        5215         5750      5765       5780      $
}
#p2p_disabled=1
ignore_old_scan_res=1

```

btw, should SPI be showing up in /dev or not?
![image](https://user-images.githubusercontent.com/1147662/115932176-18e9f400-a495-11eb-8101-98bc9f8c0c08.png)

**Comment by droidifi** [comment]
This is a SPI slave. Only a SPI master would show up in /dev. 

I've ordered one of the Alpha Network AHPI7292S Pihat modules and asked for a copy of the schematic.

I used Silex modules for development and there may be some differences.

**Comment by droidifi** [comment]
I fixed an issue with EU country settings and have uploaded a new patch and Raspberry Pi image. The new image defaults to EU for the firmware and FI for hostapd and wpa_supplicant.

**Comment by Zeddy-** [comment]
Thank you very much, i will try it out and keep you updated!

**Comment by Zeddy-** [comment]
![image](https://user-images.githubusercontent.com/1147662/116566868-c5056200-a90f-11eb-8d4d-85a3c25b6ad3.png)

So still no luck. AP and client both seem to start fine. But the clien't wont connect to the AP.

This is what iw list gives me:

```
pi@raspberrypi:~ $ iw phy
Wiphy nrc80211
        max # scan SSIDs: 4
        max scan IEs length: 2266 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports RSN-IBSS.
        Device supports AP-side u-APSD.
        Supported Ciphers:
                * CCMP-128 (00-0f-ac:4)
                * CCMP-256 (00-0f-ac:10)
                * CMAC (00-0f-ac:6)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * P2P-device
        Band 5:
                Capabilities: 0x0c
                        HT20
                        SM Power Save disabled
                        No RX STBC
                        Max AMSDU length: 3839 bytes
                        No DSSS/CCK HT40
                Maximum RX AMPDU length 8191 bytes (exponent: 0x000)
                Minimum RX AMPDU time spacing: No restriction (0x00)
                HT TX/RX MCS rate indexes supported: 0-7
                Bitrates (non-HT):
                        * 1.0 Mbps
                        * 2.0 Mbps (short preamble supported)
                        * 4.0 Mbps (short preamble supported)
                Frequencies:
                        * 863 MHz [-308] (20.0 dBm)
                        * 864 MHz [-308] (20.0 dBm)
                        * 865 MHz [-308] (20.0 dBm)
                        * 866 MHz [-308] (20.0 dBm)
                        * 867 MHz [-308] (20.0 dBm)
                        * 864 MHz [-308] (disabled)
                        * 866 MHz [-308] (20.0 dBm)
 Supported commands:
                 * new_interface
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * new_mpath
                 * set_mesh_config
                 * set_bss
                 * authenticate
                 * associate
                 * deauthenticate
                 * disassociate
                 * join_ibss
                 * join_mesh
                 * remain_on_channel
                 * set_tx_bitrate_mask
                 * frame
                 * frame_wait_cancel
                 * set_wiphy_netns
                 * set_channel
                 * set_wds_peer
                 * probe_client
                 * set_noack_map
                 * register_beacons
                 * start_p2p_device
                 * set_mcast_rate
                 * connect
                 * disconnect
                 * channel_switch
                 * set_qos_map
                 * set_multicast_to_unicast
        software interface modes (can always be added):
                 * AP/VLAN
                 * monitor
        valid interface combinations:
                 * #{ managed, AP, mesh point } <= 2,
                   total <= 2, #channels <= 1, STA/AP BI must match
        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing
        Device supports TX status socket option.
        Device supports HT-IBSS.
        Device has client inactivity timer.
        Device supports SAE with AUTHENTICATE command
        Device supports low priority scan.
        Device supports scan flush.
        Device supports AP scan.
        Device supports per-vif TX power setting
        Driver supports full state transitions for AP/GO clients
        Driver supports a userspace MPM
        Device supports configuring vdev MAC-addr on create.
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0                                                                                                                                                              0xb0 0xc0 0xd0 0xe0 0xf0

```

**Comment by droidifi** [comment]
Hmm, I have it running here without any issues. Make sure wpa_supplicant isn't running in the background and restart both daemons...?

**Comment by Zeddy-** [comment]
I have no clue why it doesn't work, i reboot, and do this:
![image](https://user-images.githubusercontent.com/1147662/116586296-fa1ab000-a921-11eb-8c11-0ce872c80bf8.png)

The only thing that comes to mind is hardware issues, but i imagine i have everything hooked up properly as i can see the adapters frequencies?

**Comment by droidifi** [comment]
The only thing that comes to mind is there is a background daemon running like wpa_supplicant that is interfering with bringing up the interfaces. 

To confirm that your hardware works I would change to the US and test channel 903.5. If that works then it is not a HW issue and you can try switching to another region.

**Comment by Zeddy-** [comment]
Hi, interestingly enough, when i change back to US and the 922000 frequency it attempted to authenticate immediately..This is a bit confusing as my module should be EU only.. 

![image](https://user-images.githubusercontent.com/1147662/116853870-6a198680-abff-11eb-9d01-f6014ea74507.png)

**Comment by Zeddy-** [comment]
Changing everything back to US does help, but seems i am required to use 915MHz with this module. 

There still seems to be some error with authentication,also even though the AP is set to broadcast on 915000, the client is trying to connect on 902.5MHz? 

```
wlan1: SME: Trying to authenticate with 00:c0:ca:ae:70:50 (SSID='droidifi' freq=902.5 MHz)
EAPOL: External notification - portValid=0
wlan1: State: SCANNING -> AUTHENTICATING
nl80211: Authenticate (ifindex=4)
  * bssid=00:c0:ca:ae:70:50
  * freq=902.5
  * freq_offset=902.5
  * SSID=droidifi
  * IEs - hexdump(len=0): [NULL]
  * auth_data - hexdump(len=102): 01 00 00 00 13 00 7d b7 ef 35 f1 6e 75 28 b6 29 42 ef f3 d9 36 c5 8f d1 8f 2d d2 02 7b e6 99 4d c3 d6 d2 71 8d d5 e2 1c 89 e2 32 b7 88 bf af 76 66 0a 6a 91 37 c3 38 cd 6b 6d 82 6d a0 bc 43 32 91 23 4b e3 df c9 ac 9e 94 12 9f 32 0b 0b 98 2d 25 03 14 3b c1 a8 e3 b4 96 76 af 44 46 36 f0 11 e6 96 2f cd 2b 1a
  * Auth Type 4
nl80211: Authentication request send successfully
nl80211: Drv Event 19 (NL80211_CMD_NEW_STATION) received for wlan1
nl80211: New station 00:c0:ca:ae:70:50
wlan1: SME: Authentication timeout
wpa_driver_nl80211_deauthenticate(addr=00:c0:ca:ae:70:50 reason_code=3)
wlan1: Radio work 'sme-connect'@0x17e3608 done in 5.039994 seconds
wlan1: radio_work_free('sme-connect'@0x17e3608): num_active_works --> 0
BSSID 00:c0:ca:ae:70:50 ignore list count incremented to 2, ignoring for 10 seconds
Continuous association failures - consider temporary network disabling
wlan1: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="droidifi" auth_failures=3 duration=30 reason=CONN_FAILED
wlan1: Consecutive connection failures: 6 --> request scan in 10000 ms
wlan1: Setting scan request: 10.000000 sec
wlan1: State: AUTHENTICATING -> DISCONNECTED
nl80211: Set wlan1 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=4 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
nl80211: Drv Event 20 (NL80211_CMD_DEL_STATION) received for wlan1
nl80211: Delete station 00:c0:ca:ae:70:50
nl80211: Drv Event 39 (NL80211_CMD_DEAUTHENTICATE) received for wlan1
nl80211: Deauthenticate event
wlan1: Event DEAUTH (11) received
wlan1: Deauthentication notification
wlan1:  * reason 3 (DEAUTH_LEAVING) locally_generated=1
wlan1:  * address 00:c0:ca:ae:70:50
Deauthentication frame IE(s) - hexdump(len=0): [NULL]
wlan1: Auto connect enabled: try to reconnect (wps=0/0 wpa_state=0)
wlan1: Do not request new immediate scan
wlan1: WPA: Clear old PMK and PTK
wlan1: Disconnect event - remove keys
wlan1: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan1 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=4 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
EAPOL: External notification - portEnabled=0
EAPOL: External notification - portValid=0
EAPOL: External notification - EAP success=0

```

Scanning networks on the client also yields results:
`pi@raspberrypi:~ $ sudo ifconfig wlan1 up
pi@raspberrypi:~ $ sudo iwlist wlan1 scan
wlan1     Scan completed :
          Cell 01 - Address: 00:C0:CA:AE:70:50
                    Frequency:902 kHz
                    Frequency:902 MHz (Channel 112)
                    Quality=35/70  Signal level=-75 dBm
                    Encryption key:on
                    ESSID:"droidifi"
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=00000000d37fd430
                    Extra: Last beacon: 852ms ago
                    IE: Unknown: 000864726F6964696669
                    IE: Unknown: 01088C129824B048606C
                    IE: Unknown: 030100
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : unknown (8)
                    IE: Unknown: 2D1A0000000000000000000000000000000000000000000000000000
                    IE: Unknown: 3D1600000000000000000000000000000000000000000000
                    IE: Unknown: 7F080000000000000000
                    IE: Unknown: DD180050F2020101000003A4000027A4000042435E0062322F00

`

But from here i also see the wrong channel 112 being used 902MHz, but the AP itself thinks it's at 915
![image](https://user-images.githubusercontent.com/1147662/116865495-6c391080-ac12-11eb-9616-ee57e6a83a20.png)

**Comment by Zeddy-** [comment]
Changing the frequency of the AP to 922500 does change things, but even then, the authentication seems to time out


`nl80211: Authenticate (ifindex=4)
  * bssid=00:c0:ca:ae:70:50
  * freq=902.5
  * freq_offset=902.5
  * SSID=droidifi
  * IEs - hexdump(len=0): [NULL]
  * auth_data - hexdump(len=102): 01 00 00 00 13 00 25 d8 21 ea 29 03 f2 41 1d 22 08 87 d1 4b 8d 51 d8 65 d6 0f f5 92 83 8d f4 a5 5a a8 b4 b4 73 e3 e 4b cc c9 59 e0 b5 8f e8 15 59 a3 f3 eb 7a 0b 90 1c 05 31 68 3e de 4b 4f 59 4f 03 46 40 be c1 fe c8 62 db 1b ce a0 6d cb e4 ab 93 4e c3 d4 9a 99 20 5 73 63 b6 de 8f 44 0e a6 fb 2f 2c
  * Auth Type 4
nl80211: Authentication request send successfully
nl80211: Drv Event 19 (NL80211_CMD_NEW_STATION) received for wlan1
nl80211: New station 00:c0:ca:ae:70:50
wlan1: SME: Authentication timeout
`

**Comment by Zeddy-** [comment]
So i gave it some time, reflashed two sd cards, put them in, and it worked straight out of the box. Seems i did something wrong the last time!

**Comment by Zeddy-** [comment]
Now i have another issue, trying to route traffic from the AP eth0 to client does not seem to work, it can ping the access point from the client. But it can't reach outside of the network, tried setting this up according to this, but does not seem to help: https://drive.google.com/file/d/0By3r0jR6h8ekYnpPak9kV1NsQkU/view 

should routing be enabled by default, and is there any other settings required to get it working?

**Comment by droidifi** [comment]
Awesome that you have it working!

Their are a few ways to route between networks. One method would be to add an Ethernet bridge interface (i.e. br0) and add the Wifi and Ethernet devices to the bridge device. But this would be only for internal LAN communication.

What I think you want to do is use the Ethernet port for Internet access. You can do this via the following commands (note: this assumes your Ethernet device received an IP address via DHCP and is the default route):

sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
sudo iptables -A INPUT -j ACCEPT

Note that there are better ways to do this if you want a proper firewall in place. One method would be to enable ufw ('uncomplicated firewall').

https://linuxize.com/post/how-to-setup-a-firewall-with-ufw-on-ubuntu-20-04/

**Comment by Zeddy-** [comment]
Thank you very much, i will give this a try, allthough i did play around with the MASQUERADE part, but perhaps i overcomplicated it.  Btw this method expects that the ip addresses of both halow devices to be inside the main networks range, correct?

**Comment by Zeddy-** [comment]
Didn't get this to work, reflashed both devices and set the AP to run these commands upon boot, but no workie. I also tried setting their ip addresses to match the rest of the network, but that ended up badly (reason i reflashed)

**Comment by Zeddy-** [comment]
Hi, just came back to this now that i had more time, this tutorial helped me get it working, with a few modifications, but for anyone else stuck here you go: https://howchoo.com/pi/setup-a-raspberry-pi-wireless-access-point

**Comment by Zeddy-** [comment]
Hi @droidifi do you know if the adapter supports meshing? I tried setting it up because i saw "mesh point" was supported, but ran into this: 

nl80211: Failed to set interface into IBSS mode

With these settings:
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
fast_reauth=1
country=FI
update_config=1
ap_scan=2
network={
    mode=1
    ssid="droidifi"
    key_mgmt=NONE
    ieee80211w=2
}

Any idea how to get it working or if it is even possible?

**Comment by droidifi** [comment]
The latest firmware does support mesh. I will have an update with the latest changes in a couple of days.

**Comment by Zeddy-** [comment]
Hi,

Did you post the update somewhere?

**Comment by huhanwj** [comment]
Hi Zeddy,

I was using the same alfa network board as you but I could not even make the board work as `dmesg` gives

```
nrc-cspi: probe of spi0.0 failed with error -22
failed to initialize hif
nrc80211: probe of nrc80211 failed with error -22
```

Could you tell me which RPi do you use? I'm using a RPi 4B 4GB version.

**Comment by huhanwj** [comment]
> Hi Zeddy,
> 
> I was using the same alfa network board as you but I could not even make the board work as `dmesg` gives
> 
> ```
> nrc-cspi: probe of spi0.0 failed with error -22
> failed to initialize hif
> nrc80211: probe of nrc80211 failed with error -22
> ```
> 
> Could you tell me which RPi do you use? I'm using a RPi 4B 4GB version.

Just use 2 3B+ and everything is fine.

btw, thanks for the AP tutorial found by @Zeddy- , it really helps.
